name: Trigger auto deployment for ca-tm2lab-bip-todo-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ master ]
    paths:
    - 'apps/part3/backend/DockerFile/**'
    - '.github/workflows/ca-tm2lab-bip-todo-backend-AutoDeployTrigger-9c77f65f-0816-4923-9378-ef14ec2234e2.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: crbiptm2labtest01.azurecr.io
          username: ${{ secrets.CATM2LABBIPTODOBACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.CATM2LABBIPTODOBACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: crbiptm2labtest01.azurecr.io/ca-tm2lab-bip-todo-backend:${{ github.sha }}
          file: ./apps/part3/backend/Dockerfile
          context: ./apps/part3/backend/


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CATM2LABBIPTODOBACKEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ca-tm2lab-bip-todo-backend -g tm2-rg-dev1-application-bip-01 --image crbiptm2labtest01.azurecr.io/ca-tm2lab-bip-todo-backend:${{ github.sha }}
